---
- name: Playbook to get python version
  hosts: all
  gather_facts: false
  tasks:
    - name: Python version
      ansible.builtin.command:
        cmd: 'python --version'
      register: pythonversion
    - name: Displaying python version
      ansible.builtin.debug:
       msg: "{{pythonversion.stdout}}"